// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_ocWbMBspqhJO4piW_qGLCPZl3xeO94',
    appId: '1:975040949644:web:1a229cdf0edf74c0567aa9',
    messagingSenderId: '975040949644',
    projectId: 'todolist-313db',
    authDomain: 'todolist-313db.firebaseapp.com',
    storageBucket: 'todolist-313db.firebasestorage.app',
    measurementId: 'G-XC5FQ9RNZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCj0iAOFr709yXL24upVr3g6z5LEiAW5E',
    appId: '1:975040949644:android:fd102836c165314c567aa9',
    messagingSenderId: '975040949644',
    projectId: 'todolist-313db',
    storageBucket: 'todolist-313db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEL7Gr-hyfAajo83S1m6xDdXtSZpb_W-8',
    appId: '1:975040949644:ios:661a5c4be0396eaf567aa9',
    messagingSenderId: '975040949644',
    projectId: 'todolist-313db',
    storageBucket: 'todolist-313db.firebasestorage.app',
    iosBundleId: 'com.example.projectUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEL7Gr-hyfAajo83S1m6xDdXtSZpb_W-8',
    appId: '1:975040949644:ios:661a5c4be0396eaf567aa9',
    messagingSenderId: '975040949644',
    projectId: 'todolist-313db',
    storageBucket: 'todolist-313db.firebasestorage.app',
    iosBundleId: 'com.example.projectUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_ocWbMBspqhJO4piW_qGLCPZl3xeO94',
    appId: '1:975040949644:web:0ff62500d7cc8f04567aa9',
    messagingSenderId: '975040949644',
    projectId: 'todolist-313db',
    authDomain: 'todolist-313db.firebaseapp.com',
    storageBucket: 'todolist-313db.firebasestorage.app',
    measurementId: 'G-SSLP144NP0',
  );
}
